# Azure pipelines mulit-stage deployment script for IIS applications

stages:
  # =========================== STAGE: Build =============================================
  - stage: Build
    jobs:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/azurepipelines/v4/legacyV4Systems/build-template.yml
  # =========================== STAGE: Azure CI/CD ========================================
  - stage: AzureTestDeployment
    displayName: "Azure CI/CD"
    dependsOn:
      - Build
    condition: succeeded('Build')
    jobs:
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/instance/azure')) }}: # @TODO: Change this to the correct branch
          - template: ${{variables['System.DefaultWorkingDirectory']}}/azurepipelines/v4/azv4-template-prod.yml
      - ${{ else }}:
          - template: ${{variables['System.DefaultWorkingDirectory']}}/azurepipelines/v4/azv4-template-nonProd.yml
